// Generated by tools/size_lab/export_fixtures.py from POC candidates.
// Developer fixture only; assets/levels.json is unchanged.
import '../features/game/models/level.dart';

const sizeLabLevels = <Level>[
  // ЛОСКУТ: 6×6, 7 words
  Level(
    id: 901,
    letters: <String>['К', 'Л', 'О', 'С', 'Т', 'У'],
    words: <WordPlacement>[
      WordPlacement(text: 'ЛОСКУТ', row: 0, col: 2, down: true),
      WordPlacement(text: 'СТУЛ', row: 2, col: 2, down: false),
      WordPlacement(text: 'СТОЛ', row: 5, col: 1, down: false),
      WordPlacement(text: 'КОЛ', row: 0, col: 5, down: true),
      WordPlacement(text: 'ТОК', row: 3, col: 0, down: false),
      WordPlacement(text: 'УКОЛ', row: 2, col: 4, down: true),
      WordPlacement(text: 'СКОТ', row: 0, col: 0, down: true),
    ],
  ),
  // КРАСОТА: 7×7, 8 words
  Level(
    id: 902,
    letters: <String>['А', 'А', 'К', 'О', 'Р', 'С', 'Т'],
    words: <WordPlacement>[
      WordPlacement(text: 'КРАСОТА', row: 3, col: 0, down: false),
      WordPlacement(text: 'СТРОКА', row: 1, col: 1, down: true),
      WordPlacement(text: 'ТОРС', row: 3, col: 5, down: true),
      WordPlacement(text: 'КАРА', row: 5, col: 3, down: false),
      WordPlacement(text: 'СОК', row: 3, col: 3, down: true),
      WordPlacement(text: 'АСТРА', row: 1, col: 0, down: false),
      WordPlacement(text: 'РАК', row: 6, col: 0, down: false),
      WordPlacement(text: 'КОРА', row: 0, col: 6, down: true),
    ],
  ),
  // РОДИНКА: 8×8, 9 words
  Level(
    id: 903,
    letters: <String>['А', 'Д', 'И', 'К', 'Н', 'О', 'Р'],
    words: <WordPlacement>[
      WordPlacement(text: 'РОДИНКА', row: 4, col: 0, down: false),
      WordPlacement(text: 'РОДНИК', row: 2, col: 2, down: true),
      WordPlacement(text: 'НАРОД', row: 2, col: 0, down: false),
      WordPlacement(text: 'РОДИНА', row: 0, col: 4, down: true),
      WordPlacement(text: 'НОРКА', row: 2, col: 0, down: true),
      WordPlacement(text: 'ДРАКОН', row: 2, col: 6, down: true),
      WordPlacement(text: 'КОРА', row: 0, col: 2, down: false),
      WordPlacement(text: 'ИКРА', row: 7, col: 1, down: false),
      WordPlacement(text: 'РОК', row: 6, col: 5, down: false),
    ],
  ),
  // ОРКЕСТР: 10×10, 14 words
  Level(
    id: 904,
    letters: <String>['Е', 'К', 'О', 'Р', 'Р', 'С', 'Т'],
    words: <WordPlacement>[
      WordPlacement(text: 'ОРКЕСТР', row: 0, col: 4, down: true),
      WordPlacement(text: 'КОРСЕТ', row: 6, col: 2, down: false),
      WordPlacement(text: 'ТРЕСК', row: 3, col: 2, down: false),
      WordPlacement(text: 'СРОК', row: 0, col: 6, down: true),
      WordPlacement(text: 'ТОРС', row: 0, col: 3, down: false),
      WordPlacement(text: 'КОТ', row: 1, col: 2, down: true),
      WordPlacement(text: 'СОК', row: 1, col: 0, down: false),
      WordPlacement(text: 'СКОТ', row: 1, col: 0, down: true),
      WordPlacement(text: 'ТРОС', row: 6, col: 7, down: true),
      WordPlacement(text: 'КРОТ', row: 6, col: 2, down: true),
      WordPlacement(text: 'РОСТ', row: 8, col: 1, down: false),
      WordPlacement(text: 'КОРТ', row: 8, col: 6, down: false),
      WordPlacement(text: 'СОРТ', row: 5, col: 9, down: true),
      WordPlacement(text: 'РОК', row: 1, col: 6, down: false),
    ],
  ),
  // РОСТОК: 7×8, 8 words
  Level(
    id: 905,
    letters: <String>['К', 'О', 'О', 'Р', 'С', 'Т'],
    words: <WordPlacement>[
      WordPlacement(text: 'РОСТОК', row: 2, col: 3, down: true),
      WordPlacement(text: 'СРОК', row: 2, col: 2, down: false),
      WordPlacement(text: 'ТРОС', row: 5, col: 3, down: false),
      WordPlacement(text: 'СОРТ', row: 4, col: 5, down: true),
      WordPlacement(text: 'СКОТ', row: 7, col: 2, down: false),
      WordPlacement(text: 'ТОРС', row: 4, col: 0, down: false),
      WordPlacement(text: 'СОК', row: 3, col: 1, down: true),
      WordPlacement(text: 'РОК', row: 0, col: 5, down: true),
    ],
  ),
  // ОСТАНКИ: 8×9, 14 words
  Level(
    id: 906,
    letters: <String>['А', 'И', 'К', 'Н', 'О', 'С', 'Т'],
    words: <WordPlacement>[
      WordPlacement(text: 'ОСТАНКИ', row: 2, col: 6, down: true),
      WordPlacement(text: 'ТАКСИ', row: 8, col: 2, down: false),
      WordPlacement(text: 'ОСИНА', row: 6, col: 3, down: false),
      WordPlacement(text: 'КОСА', row: 5, col: 3, down: true),
      WordPlacement(text: 'КИНО', row: 2, col: 3, down: false),
      WordPlacement(text: 'НОТА', row: 4, col: 4, down: false),
      WordPlacement(text: 'ТАНК', row: 5, col: 0, down: false),
      WordPlacement(text: 'СКОТ', row: 2, col: 0, down: true),
      WordPlacement(text: 'КОТ', row: 3, col: 0, down: false),
      WordPlacement(text: 'ТОН', row: 3, col: 2, down: true),
      WordPlacement(text: 'СОН', row: 0, col: 5, down: true),
      WordPlacement(text: 'СОК', row: 0, col: 5, down: false),
      WordPlacement(text: 'ИСК', row: 0, col: 3, down: true),
      WordPlacement(text: 'НОС', row: 1, col: 1, down: false),
    ],
  ),
  // ОТПРЫСК: 8×10, 14 words
  Level(
    id: 907,
    letters: <String>['К', 'О', 'П', 'Р', 'С', 'Т', 'Ы'],
    words: <WordPlacement>[
      WordPlacement(text: 'ОТПРЫСК', row: 3, col: 2, down: true),
      WordPlacement(text: 'СПОРТ', row: 8, col: 2, down: false),
      WordPlacement(text: 'ТОРС', row: 3, col: 1, down: false),
      WordPlacement(text: 'ПОРТ', row: 6, col: 5, down: true),
      WordPlacement(text: 'СОК', row: 3, col: 4, down: true),
      WordPlacement(text: 'ОПЫТ', row: 4, col: 4, down: false),
      WordPlacement(text: 'КОТ', row: 2, col: 7, down: true),
      WordPlacement(text: 'КОРТ', row: 6, col: 0, down: false),
      WordPlacement(text: 'КРОТ', row: 6, col: 0, down: true),
      WordPlacement(text: 'ПОТ', row: 6, col: 5, down: false),
      WordPlacement(text: 'РОК', row: 2, col: 5, down: false),
      WordPlacement(text: 'СЫР', row: 0, col: 5, down: true),
      WordPlacement(text: 'РОСТ', row: 0, col: 3, down: false),
      WordPlacement(text: 'ТОК', row: 9, col: 0, down: false),
    ],
  ),
];

const sizeLabNames = <String>[
  'ЛОСКУТ',
  'КРАСОТА',
  'РОДИНКА',
  'ОРКЕСТР',
  'РОСТОК',
  'ОСТАНКИ',
  'ОТПРЫСК',
];
