"""Export selected generator candidates to standalone, dev-only Dart fixtures."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "tools/level_generator/play_lab_output_compact/candidates.json"
TARGET = ROOT / "lib/dev/play_lab_levels.dart"


def main():
    candidates = json.loads(SOURCE.read_text(encoding="utf-8"))["candidates"]
    if [item["word_count"] for item in candidates] != list(range(8, 19)):
        raise ValueError("Play Lab requires exactly one candidate for each word count 8..18")
    lines = [
        "// Generated by tools/level_generator/export_play_lab.py; developer-only fixtures.",
        "// Do not copy into assets/levels.json.",
        "import '../features/game/models/level.dart';",
        "",
        "const playLabLevels = <Level>[",
    ]
    for item in candidates:
        count = item["word_count"]
        m = item["metrics"]
        lines.append(f"  // {count} words · {item['letters']} · {m['width']}×{m['height']}")
        lines.append(f"  Level(id: {1000 + count}, letters: <String>[{', '.join(repr(ch) for ch in item['letters'])}], words: <WordPlacement>[")
        for word in item["placements"]:
            lines.append(f"    WordPlacement(text: '{word['word']}', row: {word['row']}, col: {word['col']}, down: {'true' if word['direction'] == 'down' else 'false'}),")
        lines.append("  ]),")
    lines.extend(["];"])
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(TARGET)


if __name__ == "__main__":
    main()
