"""Freeze existing generator candidates as dev-only Dart Level fixtures."""

from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[2]
SOURCES = (
    ("experiment_6_7_output/candidates.json", "ЛОСКУТ", 6, 6, None),
    ("experiment_6_7_output/candidates.json", "КРАСОТА", 7, 7, None),
    ("experiment_6_7_output/candidates.json", "РОДИНКА", 8, 8, None),
    ("size_lab_search/candidates.json", "ОРКЕСТР", 10, 10, None),
    ("experiment_6_7_output/per_count_best.json", "РОСТОК", 7, 8, 8),
    ("size_lab_search/candidates.json", "ОСТАНКИ", 8, 9, None),
    ("size_lab_search/candidates.json", "ОТПРЫСК", 8, 10, None),
)


def main():
    blocks = [
        "// Generated by tools/size_lab/export_fixtures.py from POC candidates.",
        "// Developer fixture only; assets/levels.json is unchanged.",
        "import '../features/game/models/level.dart';",
        "",
        "const sizeLabLevels = <Level>[",
    ]
    for index, (source, seed, width, height, count) in enumerate(SOURCES, 1):
        path = ROOT / "tools/level_generator" / source
        data = json.loads(path.read_text(encoding="utf-8"))
        candidates = data["candidates"] if count is None else [
            item["best_by_word_count"][str(count)]
            for item in data["letter_sets"] if item["seed"] == seed
        ]
        matches = [c for c in candidates if c["seed"] == seed and c["metrics"]["width"] == width and c["metrics"]["height"] == height]
        if len(matches) != 1:
            raise ValueError(f"Expected one {seed} {width}x{height} candidate in {path}; got {len(matches)}")
        item = matches[0]
        blocks.append(f"  // {seed}: {width}×{height}, {len(item['used'])} words")
        blocks.append(f"  Level(id: {900 + index}, letters: <String>[{', '.join(repr(ch) for ch in item['letters'])}], words: <WordPlacement>[")
        for p in item["placements"]:
            blocks.append(f"    WordPlacement(text: '{p['word']}', row: {p['row']}, col: {p['col']}, down: {'true' if p['direction'] == 'down' else 'false'}),")
        blocks.append("  ]),")
    blocks.append("];")
    blocks.append("")
    blocks.append("const sizeLabNames = <String>[" + ", ".join(repr(source[1]) for source in SOURCES) + "];")
    target = ROOT / "lib/dev/size_lab_levels.dart"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(blocks) + "\n", encoding="utf-8")
    print(target)


if __name__ == "__main__":
    main()
